export {
  archiveIncident,
  checkIncidentDuplicate,
  commitAforImport,
  createIncident,
  createRegionalIncident,
  deleteDraft,
  deleteIncident,
  fetchIncident,
  fetchIncidents,
  fetchRegionalIncident,
  fetchRegionalIncidents,
  fetchRegionalStats,
  fetchValidatorStats,
  forceReplaceIncident,
  importAforFile,
  listEncoderDrafts,
  submitIncidentForReview,
  unpendIncident,
  updateDraft,
  updateRegionalIncident,
} from './legacy';

export type {
  AforCommitResult,
  AforFormKind,
  AforImportPreviewResponse,
  DraftSummary,
  DuplicateAction,
  DuplicateInfo,
  RefDuplicateIncident,
  RegionalIncidentDetailResponse,
  RegionalIncidentListItem,
  RegionalIncidentsListResponse,
  RegionalIncidentsQueryParams,
  RowResolution,
  WildlandRowSource,
} from './legacy';
